version: '2'
services:
  eolotest-app:
    image: eolotest
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://eolotest-postgresql:5432/EoloTest
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://eolotest-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://eolotest-elasticsearch:9200
    ports:
      - 8080:8080
  eolotest-postgresql:
    extends:
      file: postgresql.yml
      service: eolotest-postgresql
  eolotest-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: eolotest-elasticsearch
