version: '2'
services:
  eolotest-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/EoloTest/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=EoloTest
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
